const PACKAGES_PAGE_ID: string = '160587';
const ACTIVITIES_PAGE_ID: string = '160586';
const FLIGHT_HOTEL_PAGE_ID: string = '160585';
const FLIGHT_PAGE_ID: string = '160584';
const HOTEL_PAGE_ID: string = '160583';
const TRAVELGUIDE_PAGE_ID: string = '160605';

const GENERAL_HOMEPAGE_PAGE_ID: string = '160606';
const GENERAL_FLIGHT_PAGE_ID: string = '160607';
const GENERAL_PACKAGES_PAGE_ID: string = '160612';
const GERNERAL_ACTIVITIES_PAGE_ID: string = '160610';
const GENERAL_FLIGHT_HOTEL_PAGE_ID: string = '160609';
const GENERAL_HOTEL_PAGE_ID: string = '160608';
const GENERAL_TRANSFERS_PAGE_ID: string = '160611';
const GENERAL_ROUTING_PAGE_ID: string = '160613';
const GENERAL_TRAVELGUIDE_PAGE_ID: string = '160614';
const GENERAL_TRIPDESIGNER_PAGE_ID: string = '160615';

export {
    PACKAGES_PAGE_ID,
    ACTIVITIES_PAGE_ID,
    FLIGHT_HOTEL_PAGE_ID,
    FLIGHT_PAGE_ID,
    HOTEL_PAGE_ID,
    TRAVELGUIDE_PAGE_ID,

    GENERAL_HOMEPAGE_PAGE_ID,
    GENERAL_PACKAGES_PAGE_ID,
    GERNERAL_ACTIVITIES_PAGE_ID,
    GENERAL_FLIGHT_HOTEL_PAGE_ID,
    GENERAL_FLIGHT_PAGE_ID,
    GENERAL_HOTEL_PAGE_ID,
    GENERAL_TRAVELGUIDE_PAGE_ID,
    GENERAL_TRANSFERS_PAGE_ID,
    GENERAL_ROUTING_PAGE_ID,
    GENERAL_TRIPDESIGNER_PAGE_ID
};