const TRIP_DESIGNER_ROW_LIMIT: any = 6;
const TRIP_DESIGNER_PASSENGERS_LIMIT: any = 9;
const FLIGHT_PASSENGERS_LIMIT: any = 9;
const HOTEL_PASSENGERS_LIMIT: any = 15;
const HOTEL_FLIGHT_PASSENGERS_LIMIT: number = 9;
const ACTIVITIES_LIMIT: any = 15;
const TRANSFERS_LIMIT: any = 54;
const ROUNTING_LIMIT: number = 9;

export {
    TRIP_DESIGNER_ROW_LIMIT,
    TRIP_DESIGNER_PASSENGERS_LIMIT,
    FLIGHT_PASSENGERS_LIMIT,
    HOTEL_PASSENGERS_LIMIT,
    HOTEL_FLIGHT_PASSENGERS_LIMIT,
    ACTIVITIES_LIMIT,
    TRANSFERS_LIMIT,
    ROUNTING_LIMIT
};