export { default as HeroHeader} from './HeroHeader/HeroHeader';
export { default as TripIdeas} from './TripIdeas/TripIdeas';
export { default as Information} from './Information/Information';
export { default as SectionBackground} from './SectionBackground/SectionBackground';
export { default as TopInternationalDestinations} from  './TopInterDestinations/TopInternDestinations';
export { default as CheapestFlights} from './CheapestFlights/CheapestFlights';
export { default as BrowserProperty} from './BrowserProperty/BrowserProperty';
export { default as TravelBlog} from './TravelBlog/TravelBlog';
export { default as Footer} from './Footer/Footer';
export { default as PrevNext } from './PrevNext/index';
export { SEOHelmet } from './SEOHelmet';