const COUNTRIES: string = "COUNTRIES"
const CITIES: string = "CITIES"
const AIRLINES_RESOURCE: string = "AIRLINES_RESOURCE";
const DESTINATIONS_RESOURCE: string = "DESTINATIONS_RESOURCE";
const INFORMATIONS_NODE = "INFORMATIONS_NODE";
const SUBTOPICS_TERM = "SUBTOPICS_TERM";
const HELP_TYPES_TERM = "HELP_TYPES_TERM";
const HELP_ARTICLES = "HELP_ARTICLES";
const SEARCH_NODE = "SEARCH_NODE";
const SUBTOPICS_PARAGRAPH = "SUBTOPICS_PARAGRAPH";
const TAXONOMYDIR_ACTIVE: string = "TAXONOMYDIR_ACTIVE";
const CONTINENT: string = "CONTINENT";
const CITY_DATA: string = "CITY_DATA";
const TOKEN: string = "TOKEN";
const ACTIVE_PROFILE_SIDE_MENU: string = "ACTIVE_PROFILE_SIDE_MENU";
const USER_DATA: string = "USER_DATA";
const SUPPORT_HELP: string = "SUPPORT_HELP";
const CURRENCY: string = "CURRENCY";
const GUIDE_DETAIL: string = "GUIDE_DETAIL";
const DESTINATION_DETAIL: string = "DESTINATION_DETAIL";
const TRIP_IDEA_DATA: string = "TRIP_IDEA_DATA";
const LANGUAGE: string = "LANGUAGE";
const TAXONOMY_CLEAR: string = "TAXONOMY_CLEAR";
const TAXONOMY_UPDATE: string = "TAXONOMY_UPDATE";
const HOTELS_DATA: string = "HOTELS_DATA";
const TRANSPORTS_DATA: string = "TRANSPORTS_DATA";
const RESET: string = "RESET";
const HOTEL_BY_PROVIDER_DATA: string = "HOTEL_BY_PROVIDER_DATA";
const BY_PROVIDER_DATA: string = "BY_PROVIDER_DATA";
const ACCOMODATIONS_DATA: string = "ACCOMODATIONS_DATA";
const ALL_DESTINATION_DATA: string = "ALL_DESTINATION_DATA";
const DESTINATION_DATA: string = "DESTINATION_DATA";
const DEPARTURE_DATA: string = "DEPARTURE_DATA";
const ARRIVAL_DATA: string = "ARRIVAL_DATA";
const CITIES_CLEAR: string = "CITIES_CLEAR";
const ALL_EXTERNAL_COUNTRIES: string = "ALL_EXTERNAL_COUNTRIES";
const GUIDE_DETAIL_CLEAR: string = "GUIDE_DETAIL_CLEAR";
const TRANSFERS_DATA: string = "TRANSFERS_DATA";
const HOTELS_FORM_HEIGHT = 'HOTELS_FORM_HEIGHT';
const CITY_HOTELS_DATA: string = "CITY_HOTELS_DATA";
const POPULAR_DESTINATION_VIEW: string = "POPULAR_DESTINATION_VIEW";
const SEARCH_DESTINATION: string = "SEARCH_DESTINATION";
const ACTIVE_SEARCH_GUIDE: string = "ACTIVE_SEARCH_GUIDE";
const TRANSFERS_FORM_HEIGHT: string = "TRANSFERS_FORM_HEIGHT"
const ABOUT: string = "ABOUT";
const JOBS: string = "JOBS";
const HELPS_TYPES: string = "HELPS_TYPES";
const EXCLUSIVE_OFFERS: string = "EXCLUSIVE_OFFERS";
const FLIGHTS_FORM_HEIGHT: string = "FLIGHTS_FORM_HEIGHT"
const GUESTS_INPUT_POPOVER_HEIGHT: string = "POPOVER_GUESTS_INPUT_HEIGHT"
const BOOKINGS_DATA: string = "BOOKINGS_DATA";
const OFFER_DETAIL: string = "OFFER_DETAIL";
const FAQS: string = "FAQS";
const DISCOVER_DESTINATIONS: string = "DISCOVER_DESTINATIONS";
const POPULAR_CITIES_DATA: string = "POPULAR_CITIES_DATA";
const TRAVEL_NEWS_DATA: string = "TRAVEL_NEWS_DATA";
const ACTIVITIES_DATA: string = "ACTIVITIES_DATA";
const TRAVEL_NEWS_DETAIL_DATA: string = "TRAVEL_NEWS_DETAIL_DATA";
const TRANSFERS_SEARCH_FORM_HEIGHT: string = "TRANSFERS_SEARCH_FORM_HEIGHT";
const TRAVEL_NEWS_DETAIL_CLEAR: string = "TRAVEL_NEWS_DETAIL_CLEAR";
const HAS_USER_BEEN_HERE_BEFORE: string = "HAS_USER_BEEN_HERE_BEFORE";
const HAS_USER_BEEN_HERE_BEFORE_CLEAR: string = "HAS_USER_BEEN_HERE_BEFORE_CLEAR";
const RESET_ACTIVE_USER_MENU: string = 'RESET_ACTIVE_USER_MENU'
const LANDING_PAGE_INFO: string = "LANDING_PAGE_INFO";
const MULTISTOP_HIGHT: string = "MULTISTOP_HIGHT";
const USER_TRIP_IDEAS_HISTORY: string = "USER_TRIP_IDEAS_HISTORY";
const CITIES_BUNDLES: string = "CITIES_BUNDLES";
const SEARCH_HELPS: string = "SEARCH_HELPS";
const ACTIVE_SEARCH_HELP: string = "ACTIVE_SEARCH_HELP";
const STATIC_PAGE_TEXT: string = "STATIC_PAGE_TEXT";
const SCROLL_TO_TOP: string = "SCROLL_TO_TOP";
const TRAVELLERS: string = "TRAVELLERS";
const RESET_OFFER_DETAIL: string = "RESET_OFFER_DETAIL";
const TRIP_IDEA_DATA_BY_ID: string = "TRIP_IDEA_DATA_BY_ID";
const TRANSPORTS_DATA_BY_ID: string = "TRANSPORTS_DATA_BY_ID";
const SCROLL_TO_TARGET: string = "SCROLL_TO_TARGET";
const EXCLUSIVE_OFFERS_VIEW: string = "EXCLUSIVE_OFFERS_VIEW";
const AVUXI: string = 'AVUXI';
const CITY_WEATHER_DATA: string = "CITY_WEATHER_DATA";
const DEPARTURE_DATA_RESET: string = "DEPARTURE_DATA_RESET";
const ARRIVAL_DATA_RESET: string = "ARRIVAL_DATA_RESET";
const CITY_ACTIVITIES_DATA: string = "CITY_ACTIVITIES_DATA";
const CITY_TRANSFERS_DATA: string = "CITY_TRANSFERS_DATA";
const RESET_ACCOMODATIONS_DATA: string = "RESET_ACCOMODATIONS_DATA";
const RESET_TRANSPORTS_DATA_BY_ID: string = "RESET_TRANSPORTS_DATA_BY_ID";
const RESET_CITY_ACTIVITIES_DATA: string = "RESET_CITY_ACTIVITIES_DATA";
const RESET_CITY_TRANSFERS_DATA: string = "RESET_CITY_TRANSFERS_DATA";
const RESET_TRIP_IDEA_DATA_BY_ID: string = "RESET_TRIP_IDEA_DATA_BY_ID";
const HOTELS_CARD_WIDTH: string = "HOTELS_CARD_WIDTH";
const COMPANY: string = "COMPANY";
const ACTIVE_OFFERS_SEARCH_TAB: string = "ACTIVE_OFFERS_SEARCH_TAB";
const CHANGEICON: string = "CHANGEICON";
const TRIGGER_NOTIFICATION = "TRIGGER_NOTIFICATION";
const SEARCH_BTN_STATUS: string = "SEARCH_BTN_STATUS";
const SOCIAL_LOGIN_SDK: string = "SOCIAL_LOGIN_SDK";
const SOCIAL_LOGIN_OR_SIGNUP: string = "SOCIAL_LOGIN_OR_SIGNUP";
const USER_PROFILE: string = "USER_PROFILE";
const TAB_NAME_TRIPDESIGNER: string = "TAB_NAME_TRIPDESIGNER";
const FEEDBACK: string = "FEEDBACK";

const TYPES = {
    COUNTRIES,
    AIRLINES_RESOURCE,
    DESTINATIONS_RESOURCE,
    INFORMATIONS_NODE,
    SUBTOPICS_TERM,
    HELP_TYPES_TERM,
    HELP_ARTICLES,
    SEARCH_NODE,
    SUBTOPICS_PARAGRAPH,
    TAXONOMYDIR_ACTIVE,
    CONTINENT,
    CITY_DATA,
    TOKEN,
    ACTIVE_PROFILE_SIDE_MENU,
    CITIES,
    USER_DATA,
    SUPPORT_HELP,
    CURRENCY,
    GUIDE_DETAIL,
    DESTINATION_DETAIL,
    TRIP_IDEA_DATA,
    LANGUAGE,
    TAXONOMY_CLEAR,
    TAXONOMY_UPDATE,
    HOTELS_DATA,
    TRANSPORTS_DATA,
    RESET,
    HOTEL_BY_PROVIDER_DATA,
    BY_PROVIDER_DATA,
    ACCOMODATIONS_DATA,
    ALL_DESTINATION_DATA,
    DESTINATION_DATA,
    DEPARTURE_DATA,
    ARRIVAL_DATA,
    CITIES_CLEAR,
    ALL_EXTERNAL_COUNTRIES,
    GUIDE_DETAIL_CLEAR,
    TRANSFERS_DATA,
    HOTELS_FORM_HEIGHT,
    CITY_HOTELS_DATA,
    POPULAR_DESTINATION_VIEW,
    SEARCH_DESTINATION,
    ACTIVE_SEARCH_GUIDE,
    TRANSFERS_FORM_HEIGHT,
    ABOUT,
    JOBS,
    HELPS_TYPES,
    EXCLUSIVE_OFFERS,
    FLIGHTS_FORM_HEIGHT,
    GUESTS_INPUT_POPOVER_HEIGHT,
    BOOKINGS_DATA,
    OFFER_DETAIL,
    FAQS,
    DISCOVER_DESTINATIONS,
    POPULAR_CITIES_DATA,
    TRAVEL_NEWS_DATA,
    ACTIVITIES_DATA,
    TRAVEL_NEWS_DETAIL_DATA,
    TRANSFERS_SEARCH_FORM_HEIGHT,
    TRAVEL_NEWS_DETAIL_CLEAR,
    HAS_USER_BEEN_HERE_BEFORE,
    HAS_USER_BEEN_HERE_BEFORE_CLEAR,
    RESET_ACTIVE_USER_MENU,
    LANDING_PAGE_INFO,
    MULTISTOP_HIGHT,
    USER_TRIP_IDEAS_HISTORY,
    CITIES_BUNDLES,
    SEARCH_HELPS,
    ACTIVE_SEARCH_HELP,
    STATIC_PAGE_TEXT,
    SCROLL_TO_TOP,
    RESET_OFFER_DETAIL,
    TRAVELLERS,
    TRIP_IDEA_DATA_BY_ID,
    TRANSPORTS_DATA_BY_ID,
    SCROLL_TO_TARGET,
    EXCLUSIVE_OFFERS_VIEW,
    AVUXI,
    CITY_WEATHER_DATA,
    DEPARTURE_DATA_RESET,
    ARRIVAL_DATA_RESET,
    CITY_ACTIVITIES_DATA,
    CITY_TRANSFERS_DATA,
    RESET_ACCOMODATIONS_DATA,
    RESET_TRANSPORTS_DATA_BY_ID,
    RESET_CITY_ACTIVITIES_DATA,
    RESET_CITY_TRANSFERS_DATA,
    RESET_TRIP_IDEA_DATA_BY_ID,
    HOTELS_CARD_WIDTH,
    COMPANY,
    ACTIVE_OFFERS_SEARCH_TAB,
    CHANGEICON,
    TRIGGER_NOTIFICATION,
    SEARCH_BTN_STATUS,
    SOCIAL_LOGIN_SDK,
    SOCIAL_LOGIN_OR_SIGNUP,
    USER_PROFILE,
    TAB_NAME_TRIPDESIGNER,
    FEEDBACK
};

export default TYPES;
